// Export a Mesh to OBJ, STL (ASCII) or glTF (single-file, embedded buffer).

export function toOBJ(mesh, name = "model") {
  const lines = [`# ${name} - generated by Text-to-3D`, `o ${name}`];
  // vertex positions (with non-standard but widely supported per-vertex color)
  for (let i = 0; i < mesh.positions.length; i += 3) {
    const r = mesh.colors[i] ?? 1, g = mesh.colors[i + 1] ?? 1, b = mesh.colors[i + 2] ?? 1;
    lines.push(
      `v ${f(mesh.positions[i])} ${f(mesh.positions[i + 1])} ${f(mesh.positions[i + 2])} ${f(r)} ${f(g)} ${f(b)}`
    );
  }
  for (let i = 0; i < mesh.normals.length; i += 3) {
    lines.push(`vn ${f(mesh.normals[i])} ${f(mesh.normals[i + 1])} ${f(mesh.normals[i + 2])}`);
  }
  for (let i = 0; i < mesh.indices.length; i += 3) {
    const a = mesh.indices[i] + 1, b = mesh.indices[i + 1] + 1, c = mesh.indices[i + 2] + 1;
    lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
  }
  return lines.join("\n") + "\n";
}

export function toSTL(mesh, name = "model") {
  const lines = [`solid ${name}`];
  const p = mesh.positions, idx = mesh.indices;
  for (let i = 0; i < idx.length; i += 3) {
    const ia = idx[i] * 3, ib = idx[i + 1] * 3, ic = idx[i + 2] * 3;
    const ax = p[ia], ay = p[ia + 1], az = p[ia + 2];
    const bx = p[ib], by = p[ib + 1], bz = p[ib + 2];
    const cx = p[ic], cy = p[ic + 1], cz = p[ic + 2];
    // face normal
    const ux = bx - ax, uy = by - ay, uz = bz - az;
    const vx = cx - ax, vy = cy - ay, vz = cz - az;
    let nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
    const len = Math.hypot(nx, ny, nz) || 1;
    nx /= len; ny /= len; nz /= len;
    lines.push(`  facet normal ${f(nx)} ${f(ny)} ${f(nz)}`);
    lines.push("    outer loop");
    lines.push(`      vertex ${f(ax)} ${f(ay)} ${f(az)}`);
    lines.push(`      vertex ${f(bx)} ${f(by)} ${f(bz)}`);
    lines.push(`      vertex ${f(cx)} ${f(cy)} ${f(cz)}`);
    lines.push("    endloop");
    lines.push("  endfacet");
  }
  lines.push(`endsolid ${name}`);
  return lines.join("\n") + "\n";
}

export function toGLTF(mesh, name = "model") {
  const vCount = mesh.vertexCount;
  const positions = new Float32Array(mesh.positions);
  const normals = new Float32Array(mesh.normals);
  const colors = new Float32Array(mesh.colors);
  const indices = new Uint32Array(mesh.indices);

  // bounds for POSITION accessor
  const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < positions.length; i += 3) {
    for (let k = 0; k < 3; k++) {
      const v = positions[i + k];
      if (v < min[k]) min[k] = v;
      if (v > max[k]) max[k] = v;
    }
  }

  const idxBytes = indices.byteLength;
  const posBytes = positions.byteLength;
  const nrmBytes = normals.byteLength;
  const colBytes = colors.byteLength;
  const total = idxBytes + posBytes + nrmBytes + colBytes;

  const buf = new Uint8Array(total);
  let off = 0;
  buf.set(new Uint8Array(indices.buffer), off); const idxOff = off; off += idxBytes;
  buf.set(new Uint8Array(positions.buffer), off); const posOff = off; off += posBytes;
  buf.set(new Uint8Array(normals.buffer), off); const nrmOff = off; off += nrmBytes;
  buf.set(new Uint8Array(colors.buffer), off); const colOff = off; off += colBytes;

  const gltf = {
    asset: { version: "2.0", generator: "Text-to-3D Procedural Generator" },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, name }],
    meshes: [{
      name,
      primitives: [{
        attributes: { POSITION: 1, NORMAL: 2, COLOR_0: 3 },
        indices: 0,
        material: 0,
      }],
    }],
    materials: [{
      name: "vertexColor",
      pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0.0, roughnessFactor: 0.85 },
    }],
    buffers: [{ byteLength: total, uri: "data:application/octet-stream;base64," + base64(buf) }],
    bufferViews: [
      { buffer: 0, byteOffset: idxOff, byteLength: idxBytes, target: 34963 },
      { buffer: 0, byteOffset: posOff, byteLength: posBytes, target: 34962 },
      { buffer: 0, byteOffset: nrmOff, byteLength: nrmBytes, target: 34962 },
      { buffer: 0, byteOffset: colOff, byteLength: colBytes, target: 34962 },
    ],
    accessors: [
      { bufferView: 0, componentType: 5125, count: indices.length, type: "SCALAR" },
      { bufferView: 1, componentType: 5126, count: vCount, type: "VEC3", min, max },
      { bufferView: 2, componentType: 5126, count: vCount, type: "VEC3" },
      { bufferView: 3, componentType: 5126, count: vCount, type: "VEC3" },
    ],
  };
  return JSON.stringify(gltf, null, 2);
}

function f(n) {
  return Number(n.toFixed(5)).toString();
}

function base64(bytes) {
  let bin = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
  }
  return btoa(bin);
}
